### PR TITLE
React Native 0.62 supports

### PR DESCRIPTION
**Pull request by smellman**
React Native 0.62 supports:

- [x] iOS: Supports React Native 0.62
- [x] iOS: remove GCDWebServer code and use CocoaPods denendency
- [x] Android: Supports React Native 0.62
- [x] Android: Version up based library
- [x] Example: Drop ComponentWillMount
- [x] Common: Typescript support https://github.com/futurepress/react-native-static-server/issues/67
- [x] Common: Supports ~add headers~ CORS https://github.com/futurepress/react-native-static-server/pull/66

### CODE REVIEW

**Comment by smellman** [comment]
@fchasen Can you review this PR?

**Comment by saggiyogesh** [comment]
@smellman IMO, you should fork this repo & publish the package. Maintainer of this package is not very active. 
My ios app upgrade to RN0.62 is blocked due to many installation issues with this package.

**Comment by fchasen** [comment]
Will take a look! Thanks again for this.

Sorry for the drop off on this, still haven't updated the epubjs-RN app past 0.59 so this has remained something I've been putting off for too long!

**Comment by fchasen** [comment]
This is working great, very excited to see the cors implementation.

My only concern is moving `GCDWebServer` to a cocoapod. I think we should probably keep the dependancies for that local so as to not break existing install and force people to use cocoapods (or carthage...).

**Comment by saggiyogesh** [comment]
> This is working great, very excited to see the cors implementation.
> 
> My only concern is moving `GCDWebServer` to a cocoapod. I think we should probably keep the dependancies for that local so as to not break existing install and force people to use cocoapods (or carthage...).

@fchasen With the latest RN versions 0.60+ cocoapods is a must. On one side it'll make packages up to date, while any breaking changes on `GCDWebServer` might break the server. That's how the whole modular system works. 

I think its good to go with cocoapods. Rest is your call. 
But Please update/merge this PR. 🙏

**Comment by smellman** [comment]
https://guides.cocoapods.org/syntax/podspec.html#dependency
I can fix the version of GCDWebServer.

**Comment by fchasen** [comment]
I'm new to using pods in RN but I check that the [react-native-community/bob](https://github.com/react-native-community/bob) tool for generating libraries is using a similar podspec file so I guess that's the way to go now.

I'll merge this and then lock to `pod "GCDWebServer", "~> 3.0"` before publishing the new version.

(As sidenote, they have a clever babel setup to avoid using `link:` that I'll try to bring over at some point)

Thanks again for this MR!

**Comment by danilocanalle** [comment]
Is it really working on IOS ?

**Pull request merged**
