### PR TITLE
Windows port

### PR DESCRIPTION
**Pull request by JulienNoble**
Needed a windows version of your static server running alongside the ios version, so I made one using [Restup](https://github.com/tomkuijsten/restup/). It's still very WIP, I'm making the PR so that you can check what's going on behind and discuss about it.

The implementation is just like iOS and Android : a FPStaticServer class implemented in C# with a start and stop method. Restup handles the server side, and it comes packed with a full MVC/REST architecture (that is currently not used at all) and a static file router. The MVC part is totally overkill, but the server's primary usage is for IOT on raspi, so it's pretty efficient.

By default, relative paths are rebased into your `ms-appdata:///` (app install dir), and absolute paths work too. **I have to stress out file permissions are extremely weird on UWP, so beware when you're not inside your app install dir**.

I also went and updated the RN version to `^0.49.0` and passed it as a `devDependencies` because `dependencies` and `peerDependencies` would give very weird conflicts on installing via npm/yarn on an established RN app.

Current security :

- relative paths rebase into `ms-appdata:///`
- `/` characters are replaced by `\` because... yeah, it's Windows
- server is stopped and restarted with app lifecycle

Current limitations :

- UWP target only, no WPF
- localhost only and keepAlive are currently ignored

### CODE REVIEW

**Comment by fchasen** [comment]
This is amazing! I'm sadly not setup to test it, but will try to get up to speed on it.
In the meantime, let me know when this is ready to merge.

As for the peerDependencies, the trend seems to be to just remove it so I'll do that soon.

**Comment by fchasen** [comment]
Is Restup able to serve `.opf` files ok?
The mime type isn't setup here: https://github.com/tomkuijsten/restup/blob/9eff1c583dbbf008e6aac5b00b23b4ff1381ec7e/src/WebServer/File/MimeTypeProvider.cs

**Comment by JulienNoble** [comment]
it doesn't seem to return them right now, just tested rapidly. I'll do a PR on their repo to add it! I can also include a custom version in repo if you want. Right now it's linked through nugget, the visual studio package manager

**Comment by fchasen** [comment]
I still don't have a setup to test this, so let me know if you think it is good to be merged before I'm setup on windows RN.

**Comment by JulienNoble** [comment]
yes sorry! I'm running a bit late on lots of stuff for work, and didn't get time to modify Restup's mimetypes, but I'm currently making it stable for our app. I'll ping you when it's ready, shouldn't take very long!

**Comment by JulienNoble** [comment]
hey! Sorry for the long response time. I think it's pretty stable now. Some quirks I discovered though :

- you can't access localhost on the same machine from a different process than the app, but you can call the server by its machine IP only if you are not on the same machine. This is a UWP limitation MS introduced a while ago, and it basically means `localOnly` is currently always false
- Restup hides the keep alive parameter, but it's still here. Right now, consider `keepAlive` to always be true

those 2 parameters are still in the `start()` prototype, but they aren't used on Windows. Once I get the time (sorry, this is all work related, and I've got to handle a lot of things), I'll submit a PR to their project. In the meantime, if you wish to test and validate what's here : it works very well, apart from those two options.

If you're interested, [I did a write up](http://cubeslam.net/2017/11/16/babylonjs-inside-react-native-inception-style/) on why we're using your package in our app :)

**Comment by fchasen** [comment]
This is conflicting with the 0.62 updates in #89
If anyone is using RN in Windows and gets a chance to update these changes for > RN 0.62 please reopen and I'd be happy to merge this in.

**Pull request closed without merging**
