### PR TITLE
Add homepage in package.json

### PR DESCRIPTION
**Pull request by Godefroy**
Fixes bug when executing `pod install`

Capture d’écran 2019-11-06 à 12 20 22

### CODE REVIEW

**Comment by fchasen** [comment]
Thanks! Will publish a new version shortly

**Comment by billouboq** [comment]
@fchasen thanks for merging this, do you know when this new version will be published ?

**Comment by arnaudambro** [comment]
@fchasen when can you publish a new version ?

**Comment by lucasriondel** [comment]
@fchasen can you please publish a new version ?

**Comment by mauricioholanda1** [comment]
@fchasen when can ou publish a new version?? still with this issue...

**Comment by parris** [comment]
This is still happening unfortunately - has a new version been published?

**Pull request merged**
